# support jsp
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: ems
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/111
    username: root
    password: root

# set project name
server:
  servlet:
    context-path: /ems

mybatis:
  mapper-locations:
  - classpath:com/demo/ems/mapper/*.xml   # mapper xml locations
  type-aliases-package: com.demo.ems.entity
    

